# Generated by Django 4.1.4 on 2022-12-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=200)),
                ('current_location', models.CharField(max_length=200)),
                ('skills', models.CharField(max_length=200)),
                ('langguage', models.CharField(max_length=200)),
                ('about_me', models.CharField(max_length=200)),
                ('education', models.CharField(max_length=200)),
                ('experience', models.CharField(max_length=200)),
            ],
        ),
    ]
