# Generated by Django 4.1.4 on 2022-12-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobApply', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ja',
            name='img',
            field=models.ImageField(default=0, upload_to='images/'),
            preserve_default=False,
        ),
    ]
